### ISSUE TITLE
Bug: blade files cannot be localized (Sage 10-beta.2)

### ISSUE THREAD

**Issue by SergiArias** [roots/sage#2929] opened 2022-01-04 11:18 UTC
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

In Sage 10.0.0-beta.1, all blade views were cached as php files in storage folder. Now this is not happening (I am not sure if it's intended). The problem is that I cannot use localization functions like `__('Some string', 'sage')` as they won't be catched by the pot file generator.

### Steps To Reproduce

```blade
 <h2>{!! __('Frequently asked questions', 'sage') !!}</h2>
```

### Expected Behavior

The string should be catched by the pot file generator

### Actual Behavior

The string is ignored by the pot file generator as it's not inside a php file

### Versions

10.0.0-beta-2

**Comment by SergiArias** [comment] 2022-01-04 11:52
It's related to this pull request: https://github.com/roots/sage/pull/2837
Being the views now in wp-content instead of the theme itself, how can we localize strings?

**Comment by retlehs** [comment] 2022-01-04 19:45
is this not a dupe of https://github.com/roots/sage/issues/2672#issuecomment-819676775? (it seems like paths need to be adjusted?)

can you please update this bug report to be more specific/have more details about the bug? we don't know which commands you're running to generate pot files

**Comment by SergiArias** [comment] 2022-01-04 21:07
I am using Loco Translate plugin to both generate the pot file and translate it, and it looks inside the theme files, not the wp-content ones. I will try the method mentioned in 2672 though and update the bug.

**Comment by retlehs** [comment] 2022-01-04 21:08
well that definitely makes a difference and absolutely needed to be said earlier haha

i don't think it's reasonable to expect a wordpress plugin to generate a pot file for a theme that's using blade. please followup in #2672 if you have issues with using wp-cli to generate a pot file

**Closed by retlehs** 2022-01-04 21:08 UTC
Labels: bug
