### ISSUE TITLE
Autoload JS files from /scripts/autoload/ doesn't work with import "./autoload/**/*" from main.js

### ISSUE THREAD

**Issue by ancredigital** [roots/sage#2082] opened 2018-07-07 01:13 UTC
## Submit a feature request or bug report

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Files from resources/scripts/autoload/ are not being loaded by the import "./autoload/**/*" from main.js
I'm receiving an error on a fresh install. Nothing has been changed. 

Here's the error I'm receiving in Terminal: 
 ERROR  Failed to compile with 1 errors                                                                                                                                    8:35:29 PM

 error  in ./resources/assets/scripts/main.js

Module build failed: Module failed because of a eslint error.

/resources/assets/scripts/main.js
  5:43  error  Parsing error: Unterminated string constant

✖ 1 problem (1 error, 0 warnings)

**What is the expected or desired behavior?**

All files from resources/scripts/autoload/ should be loaded and for yarn build to be successful

---

## Bug report

**Please provide steps to reproduce, including full log output:**

import "./autoload/**/*" frommain.js seems not to load files under /autoload/.

**Please describe your local environment:**

WordPress version: 4.9.6

OS: Ubuntu (64 bit) on Mac OS High Sierra Version 10.13.5

NPM/Node version: Node: v10.6.0

**Where did the bug happen? Development or remote servers?**

dev local

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

https://github.com/roots/sage/issues/1956

---

**Comment by entr** [comment] 2018-07-09 17:59
Make sure you save `resources/assets/scripts/main.js` after introducing/removing files from autoload directory

**Comment by knowler** [comment] 2018-07-19 14:02
> NPM/Node version: Node: v10.6.0

Use a lower version of Node, Sage currently is not compatible with Node 10.x (#2067).

I would recommend using [`nvm`](https://github.com/creationix/nvm) to switch between Node versions — as mentioned in the NPM Debugging Guidelines Post in the issue checklist that you did not fill out. Use NVM to install and use the current LTS version of Node (`nvm install lts/*` then `nvm use lts/*`).

I received a similar error, however, in my case it was because I broke the Webpack config file.

**Comment by MWDelaney** [comment] 2018-09-01 03:28
This hasn’t seen any action in a while. I’m closing it for now but we can re-open if the issue is still current.

**Closed by MWDelaney** 2018-09-01 03:28 UTC
