### ISSUE TITLE
npm ERR! 

### ISSUE THREAD

**Issue by c9dd** [roots/sage#1711] opened 2016-09-05 15:17 UTC
Hi 

I've just merged and I'm getting this error when running npm run build. Any iddeas why?

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! sage@9.0.0-alpha.2 build: `webpack --progress --config assets/build/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sage@9.0.0-alpha.2 build script 'webpack --progress --config assets/build/webpack.config.js'.
npm ERR! This is most likely a problem with the sage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --config assets/build/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/AMPPS/www/starter-website/wp-content/themes/cloud9-starter-2016/npm-debug.log
```

[npm-debug.log.zip](https://github.com/roots/sage/files/455283/npm-debug.log.zip)

**Comment by retlehs** [comment] 2016-09-05 15:20
how did you manage to clear out the entire new issue template when posting this? 

- [ ] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

i'm closing this since it's a personal support request that shouldn't be posted here.

**Closed by retlehs** 2016-09-05 15:20 UTC
