### ISSUE TITLE
Create GitHub Issue/PR Templates

### ISSUE THREAD

**Issue by chrisatomix** [roots/sage#1619] opened 2016-02-18 01:05 UTC
As per the new feature from GitHub:
https://github.com/blog/2111-issue-and-pull-request-templates

![Issue and Pull Request Templates](https://cloud.githubusercontent.com/assets/25792/13120859/733479fe-d564-11e5-8a1f-a03f95072f7a.png)

I'm opening this issue as a placeholder for discussion so this can be implemented as soon as possible. Anything we can do to reduce the number of support issues coming through here would be very useful.

I really like the idea of the checkboxes at the start of the issue template (as per the screenshot), perhaps something like:
- [x] I confirm that I have read the [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060)
- [x] I confirm that this is not a duplicate of an existing Issue
- [x] I confirm that I have searched the [Roots Discourse](https://discourse.roots.io/c/sage) for help
- [x] I confirm that this is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage)

There is also the ability to do the same thing for Pull Requests (with a different template).
It goes without saying that this would be useful on the Bedrock and Trellis repos too, however Sage is the one which seems to get the most personal support requests (and it's the one which floods my inbox the most often).

**Comment by Foxaii** [comment] 2016-02-18 01:22
Thanks for opening this. We've been discussing internally on Slack.

I'm in favour of the checkboxes, but you can definitely make it more DRY!!

I confirm that:
- [x] I have read the [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060)
- [x] This is not a duplicate of an existing Issue
- [x] I have searched the [Roots Discourse](https://discourse.roots.io/c/sage) for help
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage)

**Comment by chrisatomix** [comment] 2016-02-18 01:47
Much better! I'm sure there's a lot more from the Contribution Guidelines that could go in there too. Having said that, we probably wouldn't want more than 4-5 checkboxes anyway so some of these might need to be merged. I'm sure you're already way ahead of me in your Slack discussions anyway :)

**Closed** 2016-05-09 13:29 UTC
