### ISSUE TITLE
Provide a way to prevent blade rendering

### ISSUE THREAD

**Issue by davekiss** [roots/sage#1774] opened 2016-12-13 20:26 UTC
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

Blade always attempts to load a template through its own rendering engine, preventing plugins that hook into `template_include` to load their own templates at a higher priority.

https://github.com/roots/sage/blob/258d454becd8a8c8e2f60ccde90b9c82641bd0d0/src/filters.php#L46-L54

**What is the expected or desired behavior?**

Provide a way to unhook this template handling filter, or otherwise provide some check that could return the passed template path.

---

**Please provide steps to reproduce, including full log output:**

1. Add a custom filter to handle a specific usecase.

    `add_filter( 'template_include', function($template) { return 'path/to/custom/template.php' }, 9999 );`

2. Watch as the Blade filter continues to echo its own content, or throw a template not found error.

`Fatal error: Uncaught InvalidArgumentException: View [app.web.app.plugins.lunchbox.lib.frontend..default] not found. in /app/web/app/themes/cafeteria/vendor/illuminate/view/FileViewFinder.php on line 137`

**Please describe your local environment:**

WordPress version: 4.7

**Comment by QWp6t** [comment] 2016-12-13 22:10
Duplicate of #1769

**Closed by QWp6t** 2016-12-13 22:10 UTC
