### ISSUE TITLE
Disable css styles going into the admin?

### ISSUE THREAD

**Issue by vk011** [roots/sage#1657] opened 2016-05-31 09:42 UTC
Hello,

My css from frontend is getting transferred to the admin area, tinymce to be specific, any way to cancel this?

**Comment by QWp6t** [comment] 2016-05-31 11:44
Hello,

When you clicked that "New Issue" button just now, you were shown a conspicuous alert that links to our [Guidelines for Contributing](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), the first section of which is titled "[Using the Issue Tracker](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md#using-the-issue-tracker)." 

Beneath that conspicuous alert is a text field. It's the very text field that you used to write your message. That text field contained the proper format for submitting an issue. Now, we won't outright ignore all issues that don't use this formatting; it is, however, probably a good idea to at least cover the gist of it and at least make sure you're complying with our guidelines. Namely that the following are all true:

- [ ] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [ ] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Conclusion: It's clear to me that you didn't read our guidelines to contributing, nor would you have been able to check off all of the above bullets. As such, I'm going to have to close this issue.

Good bye.

**Closed by QWp6t** 2016-05-31 11:44 UTC

**Comment by QWp6t** [comment] 2016-05-31 12:20
You can change/remove editor styles here: https://github.com/roots/sage/blob/master/lib/setup.php#L47-L49

In the future, please post questions like this in our forums: https://discourse.roots.io/c/sage
