### ISSUE TITLE
[Sage 9] Backslashes in css assets urls on windows

### ISSUE THREAD

**Issue by r-moiseev** [roots/sage#1705] opened 2016-09-02 01:11 UTC
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**`

`npm run build` set images and fonts urls in css with backslashes instead of slashes and it looks like

`/wp-content/themes/sage/dist\styles\vendor\fontawesome-webfont.eot`

May be it is because I am doing it on Windows?

**What is the expected or desired behavior?**

Doing normal slashes

---

## Bug report

(delete this section if not applicable)

**Please provide steps to reproduce, including full log output:**

`npm install font-awesome`

main.css
`@import '~font-awesome/scss/font-awesome'

`npm run build```

**Please describe your local environment:**

WordPress version: 4.6

Windows 10

NPM/Node version: 3.10.3 / v6.3.1

**Where did the bug happen? Development or remote servers?**

Development

X

**Comment by QWp6t** [comment] 2016-09-02 02:40
You shouldn't have to `npm install font-awesome` with the latest version of Sage 9. [Sage 9 already comes with font-awesome](https://github.com/roots/sage/blob/master/package.json#L71).

But for good measure, I just tested this on Windows.

```
@font-face {
  font-family: 'FontAwesome';
  src: url(/app/themes/sage/dist/vendor/fontawesome-webfont_25a32416.eot);
  src: url(/app/themes/sage/dist/vendor/fontawesome-webfont_25a32416.eot?#iefix&v=4.6.3) format("embedded-opentype"), url(/app/themes/sage/dist/vendor/fontawesome-webfont_e6cf7c6e.woff2) format("woff2"), url(/app/themes/sage/dist/vendor/fontawesome-webfont_c8ddf1e5.woff) format("woff"), url(/app/themes/sage/dist/vendor/fontawesome-webfont_1dc35d25.ttf) format("truetype"), url(/app/themes/sage/dist/vendor/fontawesome-webfont_d7c63908.svg#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Looks good to me. So I'm guessing one of the following 3 scenarios is the case here:

1. You're using an older version of Sage 9, not the latest version.
2. I've already fixed this locally, in which case it will be pushed within a day or so. 
3. This is an outstanding bug, and my quick test just now simply failed to reproduce it because you and I are doing things differently.

Thoughts?

**Comment by r-moiseev** [comment] 2016-09-02 08:35
I `ve downloaded it yesterday, so there is no newer commits.  And yep, sorry for this, I use preinstalled version of fontawesome. btw, same situation with Roboto font I defined in scss

In assets/config.json i have this
```
"publicPath": "/wp-content/themes/sage",
"devUrl": "http://site.local"
```

Then i run `npm run build` and fontawesome fonts now in `dist/vendor`

But when i look in main scss there is 
```
font-face {
  font-family: 'FontAwesome';
  src: url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.eot);
  src: url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.eot) format("embedded-opentype"), url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.woff2) format("woff2"), url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.woff) format("woff"), url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.ttf) format("truetype"), url(\wp-content\themes\sage\dist\vendor/fontawesome-webfont.svg) format("svg");
  font-weight: normal;
  font-style: normal;
}
```
But browser trying to fetch realy strange url
`http://site.local/wp-content/themes/sage/dist/styles/wp-contentthemessageistvendor/fontawesome-webfont_c8ddf1e5.woff`

By the way there is my webpack.config.js
```
/ External dependencies
var webpack = require('webpack'),
    path = require('path'),
    argv = require('minimist')(process.argv.slice(2)),
    qs = require('qs'),
    autoprefixer = require('autoprefixer'),
    Clean = require("clean-webpack-plugin"),
    AssetsPlugin = require('assets-webpack-plugin'),
    ExtractTextPlugin = require('extract-text-webpack-plugin'),
    OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin'),
    cssnano = require('cssnano');

// Internal dependencies
var config = require('./assets/config');

// Internal variables
var scriptsFilename = (argv.release) ? 'scripts/[name]_[hash].js' : 'scripts/[name].js',
    stylesFilename = (argv.release) ? 'styles/[name]_[hash].css' : 'styles/[name].css',
    sourceMapQueryStr = (argv.release) ? '-sourceMap' : '+sourceMap',
    assets = 'assets/',
    dist = 'dist/',
    jsLoader,
    webpackConfig;

jsLoader = {
  test: /\.js$/,
  exclude: [ /(node_modules|bower_components)(?![/|\\](bootstrap|foundation-sites))/ ],
  loaders: [ 'babel?presets[]='+path.resolve('./node_modules/babel-preset-es2015')+'&cacheDirectory' ]
};

if (argv.watch) { // '--watch' to add monkey-hot
  jsLoader.loaders.unshift('monkey-hot');
}

/**
 * Process AssetsPlugin output and format it
 * for Sage: {"[name].[ext]":"[name]_[hash].[ext]"}
 * @param  {Object} assets passed by processOutput
 * @return {String}        JSON
 */
var assetsPluginProcessOutput = function (assets) {
  var name,
      ext,
      filename,
      results = {};

  for (name in assets) {
    if (assets.hasOwnProperty(name)) {
      for (ext in assets[name]) {
        if (assets[name].hasOwnProperty(ext)) {
          filename = name + '.' + ext;
          results[filename] = path.basename(assets[name][ext]);
        }
      }
    }
  }
  return JSON.stringify(results);
};

/**
 * Loop through webpack entry
 * and add the hot middleware
 * @param  {Object} entry webpack entry
 * @return {Object}       entry with hot middleware
 */
var addHotMiddleware = function (entry) {
  var name,
      results = {},
      hotMiddlewareScript = 'webpack-hot-middleware/client?' + qs.stringify({
        timeout: 20000,
        reload: true
      });

  for (name in entry) {
    if (entry.hasOwnProperty(name)) {
      if (entry[name] instanceof Array !== true) {
        results[name] = [entry[name]];
      } else {
        results[name] = entry[name].slice(0);
      }
      results[name].push(hotMiddlewareScript);
    }
  }
  return results;
};

webpackConfig = {
  context: path.resolve(assets),
  entry: config.entry,
  output: {
    path: path.join(__dirname, dist),
    publicPath: path.join(config.publicPath, dist),
    filename: scriptsFilename
  },
  module: {
    preLoaders: [
      {
        test: /\.js?$/,
        include: path.resolve(assets),
        loader: 'eslint'
      }
    ],
    loaders: [
      jsLoader,
      {
        test: /\.css$/,
        include: path.resolve(assets),
        loader: ExtractTextPlugin.extract('style', [
          'css?' + sourceMapQueryStr,
          'postcss'
        ])
      },
      {
        test: /\.scss$/,
        include: path.resolve(assets),
        loader: ExtractTextPlugin.extract('style', [
          'css?' + sourceMapQueryStr,
          'postcss',
          'resolve-url?' + sourceMapQueryStr,
          'sass?' + sourceMapQueryStr
        ])
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg)(\?.*)?$/,
        include: path.resolve(assets),
        loaders: [
          'file?' + qs.stringify({
            name: '[path][name].[ext]'
          }),
          'image-webpack?' + JSON.stringify({
            bypassOnDebug: true,
            progressive: true,
            optimizationLevel: 7,
            interlaced: true,
            pngquant: {
              quality: "65-90",
              speed: 4
            },
            svgo: {
              removeUnknownsAndDefaults: false,
              cleanupIDs: false
            }
          })
        ]
      },
      {
        test: /\.(ttf|eot)(\?.*)?$/,
        include: path.resolve(assets),
        loader: 'file?' + qs.stringify({
          name: '[path][name]_[md5:hash:hex:8].[ext]'
        })
      },
      {
        test: /\.woff(2)?(\?.*)?$/,
        include: path.resolve(assets),
        loader: 'url?' + qs.stringify({
          limit: 10000,
          mimetype: "application/font-woff",
          name: "[path][name]_[md5:hash:hex:8].[ext]"
        })
      },
      // Use file-loader for node_modules/ assets
      {
        test: /\.(ttf|eot|woff(2)?|png|jpg|jpeg|gif|svg)(\?.*)?$/,
        include: /node_modules/,
        loader: 'file?' + qs.stringify({
          name: 'vendor/[name]_[md5:hash:hex:8].[ext]'
        })
      }
    ]
  },
  resolve: {
    extensions: [ '', '.js', '.json' ],
    modulesDirectories: [
      'node_modules',
      'bower_components'
    ]
  },
  externals: {
    jquery: 'jQuery'
  },
  plugins: [
    new Clean([dist]),
    new ExtractTextPlugin(stylesFilename, {
      allChunks: true,
      disable: (argv.watch === true) // '--watch' disable ExtractTextPlugin
    }),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
      'Tether': 'tether',
      'window.Tether': 'tether'
    }),
    new webpack.DefinePlugin({
      WEBPACK_PUBLIC_PATH: (argv.watch === true) ? JSON.stringify(path.join(config.publicPath, dist)) : false
    })
  ],
  postcss: [
    autoprefixer({
      browsers: [
        'last 2 versions',
        'android 4',
        'opera 12'
      ]
    })
  ],
  eslint: {
    failOnWarning: false,
    failOnError: true
  },
  stats: {
    colors: true
  }
};

// '--watch' to push additional plugins to webpackConfig
if (argv.watch) {
  webpackConfig.entry = addHotMiddleware(webpackConfig.entry);
  webpackConfig.output.pathinfo = true;
  webpackConfig.debug = true;
  webpackConfig.devtool = '#cheap-module-source-map';
  webpackConfig.plugins.push(new webpack.optimize.OccurenceOrderPlugin());
  webpackConfig.plugins.push(new webpack.HotModuleReplacementPlugin());
  webpackConfig.plugins.push(new webpack.NoErrorsPlugin());
}

// '--release' to push additional plugins to webpackConfig
if (argv.release) {
  webpackConfig.plugins.push(new AssetsPlugin({
    path: path.join(__dirname, dist),
    filename: 'assets.json',
    fullPath: false,
    processOutput: assetsPluginProcessOutput
  }));
  webpackConfig.plugins.push(new webpack.optimize.UglifyJsPlugin({
    compress: {
      'drop_debugger': true
    }
  }));
  webpackConfig.plugins.push(new OptimizeCssAssetsPlugin({
    cssProcessor: cssnano,
    cssProcessorOptions: { discardComments: { removeAll: true } },
    canPrint: true
  }));
}

module.exports = webpackConfig;
```

**Comment by r-moiseev** [comment] 2016-09-03 16:31
I`ve made clear test with clean repo

```
git clone https://github.com/roots/sage.git
cd sage
npm istall
npm run  build
```

And there is same issue with backslashes

**Comment by kalenjohnson** [comment] 2016-09-03 19:57
I just ran this with Node 6.3.0 and got similar output in the CSS after running `npm run build` in Bash Cmder

`  src: url(\app\themes\sage\dist\vendor/fontawesome-webfont_25a32416.eot);`

It's probably an issue with Webpack, but since we have a kinder gentler qwp6t here, we can use him as a scapegoat

**Comment by kalenjohnson** [comment] 2016-09-03 20:06
I can also confirm that https://github.com/roots/sage/pull/1703 fixes this

`src: url(/app/themes/sage/dist/vendor/fontawesome-webfont_25a32416.eot);`

**Comment by r-moiseev** [comment] 2016-09-03 21:41
Fro now i replaced native this with laravel-elixir and it warks good

**Comment by QWp6t** [comment] 2016-09-05 02:18
I believe this is fixed now.

**Closed by QWp6t** 2016-09-05 02:18 UTC
